version: '3.8'

volumes:
  s003-v9501_lele-da-app_temp:
    external: true
  s003-v9502_lele-da-app_config:
    external: true
  s003-v9503_lele-da-app_data:
    external: true
  s003-v9105_lele-da-db:
    external: true

networks:
  s003-n01_backend_general:
    external: true
  s003-n95_lele-da:
    external: true

services:
#  s003-c9501_lele-da-app:
#    container_name: s003-c9501_lele-da-app
#    restart: unless-stopped
#    build:
#      context: ./002.04.02.04.02_DA-CodeOrchestrator
#    env_file: .env
#    ports:
#      - "${BACKEND_ORCH_BASE_PORT}:8000"
#    working_dir: /workspace/002.04.02.04.02_DA-CodeOrchestrator
#    command: uvicorn app.main:app --host 0.0.0.0 --port=8000
#
#    volumes:
#      # Mount individual directories to external volumes
#      - s003-v9503_lele-da-app_data:/workspace/002.04.02.04.02_DA-CodeOrchestrator/data
#      - s003-v9501_lele-da-app_temp:/workspace/002.04.02.04.02_DA-CodeOrchestrator/temp
#      - s003-v9502_lele-da-app_config:/workspace/002.04.02.04.02_DA-CodeOrchestrator/app/config
#
#    depends_on:
#      - s003-c9502_lele-da-front
#      - s003-c9505_lele-da-db
#    networks:
#      - s003-n95_lele-da
#
#  s003-c9502_lele-da-front:
#    container_name: s003-c9502_lele-da-front
#    restart: unless-stopped
#
#    build:
#      context: ./002.04.02.04.01_DA-CodeFrontend
#
#    env_file: .env
#    ports:
#      - "${FRONTEND_PORT}:8501"
#    working_dir: /workspace/002.04.02.04.01_DA-CodeFrontend
#    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0
#    networks:
#      - s003-n01_backend_general
#      - s003-n95_lele-da
#
  # Database service
  s003-c9505_lele-da-db:
    container_name: s003-c9505_lele-da-db
    restart: unless-stopped

    user: root
    image: postgres:13
    ports:
      - "${DB_PORT}:5432"  # HostPort:ContainerPort
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}  # Change this!
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - s003-v9105_lele-da-db:/var/lib/postgresql/data
    networks:
      - s003-n95_lele-da

#  s003-c9506_lele-da-pgpmyAdmin-db:
#    image: dpage/pgadmin4
#    container_name: s003-c9506_lele-da-pgpmyAdmin-db
#    restart: unless-stopped
#    ports:
#      - "${PGPADMIN_PORT}:80"  # Access pgAdmin at http://localhost:59503
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#    depends_on:
#      - s003-c9505_lele-da-db
#    networks:
#      - s003-n95_lele-da